[tool.poetry]
name = "simplecel"
version = "0.1.1"
description = "Excel workbook with no formula conversion, but with markdown/HTML support."
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3"
pyexcel = "^0.5.8"
flask = "^1.0"
click = "^6.7"
python-dotenv = "^0.9.0"
pyexcel-xls = "^0.5.7"

[tool.poetry.dev-dependencies]
pytest = "^3.6"
