simplecel:
  _default: {allowInsertCol: false, hasHeader: true, renderers: markdownRenderer}
  hanzi:
    allowInsertCol: false
    colHeaders: true
    colWidths: [67, 197, 200, 71, 90, 106, 66, 60, 59, 200]
    contextMenu: true
    dropdownMenu: true
    filters: true
    hasHeader: true
    manualColumnResize: true
    manualRowResize: true
    maxColWidth: 200
    renderers: markdownRenderer
    rowHeaders: true
