_default: {hasHeader: true, renderers: markdownRenderer}
hanzi:
  colHeaders: true
  colWidths: [67, 197, 200, 71, 90, 106, 66, 60, 59, 200]
  contextMenu: true
  dropdownMenu: true
  filters: true
  hasHeader: true
  manualColumnResize: true
  manualRowResize: true
  maxColWidth: 200
  renderers: markdownRenderer
  rowHeaders: true
sentences:
  colHeaders: true
  colWidths: [200, 200, 200, 200, 60, 59, 200]
  contextMenu: true
  dropdownMenu: true
  filters: true
  hasHeader: true
  manualColumnResize: true
  manualRowResize: true
  maxColWidth: 200
  renderers: markdownRenderer
  rowHeaders: true
